analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - macos/**
    - web/**
  errors:
    deprecated_member_use: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
    prefer_final_fields: true
    use_key_in_widget_constructors: true
